name: SwiftDP-Test-Framework
options:
  bundleIdPrefix: org.openmined.SwiftDP-Test-Framework
targets:
  SwiftDP-Test-Framework:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [src]
    settings:
      base:
        INFOPLIST_FILE: src/Info.plist
        OTHER_LDFLAGS: -lc++
        MARKETING_VERSION: 1
    dependencies:
      - framework: ../bazel-bin/src/SwiftDP_archive-root/SwiftDP.framework
        embed: false
