name: SwiftDP-App
options:
  bundleIdPrefix: org.openmined.SwiftDP-App
fileGroups:
  - "../bazel-OCDP/external/com_google_absl"
  - "../bazel-OCDP/external/google_differential_privacy"
targets:
  SwiftDP-App:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [app]
    preBuildScripts:
      - path: ../clang_format.sh
        name: clang-format
      - script: |
          exec "${PROJECT_DIR}/../build_framework.sh"
        name: Bazel Build Framework
    settings:
      base:
        INFOPLIST_FILE: app/Info.plist
        OTHER_LDFLAGS: -lc++
        MARKETING_VERSION: 1
        SWIFT_OBJC_BRIDGING_HEADER: app/OCDP-Bridging-Header.h
    dependencies:
      - framework: ../bazel-bin/src/OCDP_archive-root/OCDP.framework
        embed: false

  Dummy:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: ["../src"]
    settings:
      USER_HEADER_SEARCH_PATHS: "$PROJECT_DIR/../bazel-OCDP/external/**"

  SwiftDP-Unit-Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources: ["tests"]
    dependencies:
      - target: SwiftDP-App
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: app/OCDP-Bridging-Header.h
        FRAMEWORK_SEARCH_PATHS: ../bazel-bin/src/OCDP_archive-root

schemes:
  SwiftDP-App:
    build:
      targets:
        "SwiftDP-App": SwiftDP-App
    test:
      gatherCoverageData: true
      targets:
        - name: SwiftDP-Unit-Tests
          parallelizable: true
          randomExecutionOrder: true
