# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run Unit Tests"
  lane :tests do
    run_tests(project: "SwiftDP-App.xcodeproj",
              devices: ["iPhone 11"],
              code_coverage: true,
              derived_data_path: "build",
              scheme: "SwiftDP-App")
  end

  desc "Build Only"
  lane :build do
    build_app(project: "SwiftDP-App.xcodeproj",
              scheme: "SwiftDP-App",
              skip_codesigning: true,
              skip_archive: true)
  end

end